Add tests and check for each step

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,17 +8,48 @@ on:
   workflow_dispatch:
 
 jobs:
-  test1:
+  test-search-string:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Check for 'donotcommit'
+        id: check-search-string
         uses: jnguyen75/github-actions-test/actions/search-pattern@main
         with:
-          search-pattern: do*commit
-          exclude-dir: .git
+          search-pattern: donotcommit
+      - name: Check for 'donotcommit' (fail if found)
+        id: check-fail-if-found
+        continue-on-error: true
+        uses: jnguyen75/github-actions-test/actions/search-pattern@main
+        with:
+          search-pattern: donotcommit
           fail-if-found: true
+      - name: Check for 'do.*commit' pattern (fail if found)
+        id: check-search-pattern
+        continue-on-error: true
+        uses: jnguyen75/github-actions-test/actions/search-pattern@main
+        with:
+          search-pattern: do.*commit
+          fail-if-found: true
+      - name: Check Test Results
+        if: always()
+        run: |
+          code=0
+          if [[ "${{ steps.check-search-string.outcome }}" != "success" ]]; then
+            echo "Test check-search-string failed"
+            code=1
+          fi
+          if [[ "${{ steps.check-fail-if-found.outcome }}" != "failure" ]]; then
+            echo "Test check-search-string failed"
+            code=1
+          fi
+          if [[ "${{ steps.check-search-pattern }}" != "failure" ]]; then
+            echo "Test check-search-string failed"
+            code=1
+          fi
+
+          exit $code
 
 
   # notify-failure:
